[[main]]
  name = "What Am I?"
  url = "/what-am-i/"
  weight = 1

[[main]]
  name = "Machines"
  url = "/machines/"
  weight = 2

[[Machines]]
  name = "denfordlasercutter"
  url = "/machines/denfordlasercutter/"
  weight = 10

[[machines]]
  name = "HPC Laser Cutter"
  url = "/machines/hpclasercutter/"
  weight = 20

[[machines]]
  name = "Wood&Plastic Bandsaw"
  url = "/machines/woodplasticbandsaw/"
  weight = 30

[[machines]]
  name = "Belt Sander"
  url = "/machines/beltsander/"
  weight = 40

[[machines]]
  name = "Pillar Drill"
  url = "/machines/pillardrill/"
  weight = 50

[[machines]]
  name = "CNC Mill&Router"
  url = "/machines/cncmachines/"
  weight = 60

[[machines]]
  name = "Waterjet Cutter"
  url = "/machines/waterjetcutter/"
  weight = 70

[[machines]]
  name = "Hot Wire Cutter"
  url = "/machines/hotwirecutter/"
  weight = 80

[[denfordlasercutter]]
  name = "error41"
  url = "/machines/denfordlasercutter/error41/"
  weight = 10